[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "sudo apt-get update && sudo apt-get install -y libcairo2-dev pkg-config gcc",
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8003"
